server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01
    username: anishan
    password: Han123456
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true



knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        group-name: 不知道叫什么名字好
        api-rule: package
        api-rule-resources:
          - com.anishan.dome

mybatis-plus:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.anishan.dome.mybatis.entity


logging:
  level:
    com.baomidou: debug



